version: "3.8"
name: "chat-app-backend"

volumes:
  ipython_history: {}
  postgres_data:

services:
  db:
    image: postgres:latest
    container_name: chat_app_database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=chat-app-backend
      - POSTGRES_PASSWORD=chat-app-backend
      - POSTGRES_DB=chat-app-backend
      - dsro=chat-app-db
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: chat_app_redis
    ports:
      - "6379:6379"
    environment:
      - dsro=chat-app-db

  # celery:
  #   image: celery:latest
  #   container_name: celery_worker
  #   volumes:
  #     - .:/app
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=app.settings
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0

  # Use this for release
  # web:
  #   build:
  #     context: .
  #   image: chat-app-backend
  #   entrypoint: /cnb/lifecycle/launcher
  #   volumes:
  #     - .:/app
  #     - ipython_history:/root/.ipython
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=config.local_template
  #   ports:
  #     - "8000:8000"
  #   command: python3 manage.py runserver_plus 0.0.0.0:8000 --reloader-type stat
  #   depends_on:
  #     - db
  #     - redis
