# Generated by Django 4.2.5 on 2023-10-23 14:44

from django.db import migrations, models


def fill_data_for_username(apps, schema_editor):
    """Fill the username field with the email of the user."""
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        user.username = user.email
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Username"
            ),
        ),
        migrations.RunPython(
            code=fill_data_for_username,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="Username"
            ),
        )
    ]
