# Generated by Django 4.2.5 on 2023-12-11 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9]*$",
                        message="Username must be alphanumeric.",
                    )
                ],
                verbose_name="Username",
            ),
        ),
    ]
