# Generated by Django 4.2.5 on 2023-12-22 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0002_alter_message_group_alter_message_receiver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="date",
        ),
        migrations.AddField(
            model_name="message",
            name="time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Time sent",
            ),
            preserve_default=False,
        ),
    ]
