# Generated by Django 4.2.5 on 2024-01-12 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0003_remove_message_date_message_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="date_created",
        ),
    ]
